name: Kubernetes CICD
on:
  push:
    branches:
      - main

jobs:
  myapp-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      
      - name: Build docker Image
        run: "docker build -t aamirhussain3070/myapp:${GITHUB_SHA::7} ."

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
        
      - name: Push docker Image
        run: "docker push aamirhussain3070/myapp:${GITHUB_SHA::7}"
      
      - name: Install yq
        uses: mikefarah/yq@v4.44.3
      
      - name: Update K8 deployment manifest files with latest docker image
        run: |
          # Short commit hash
          SHORT_SHA=${GITHUB_SHA::7}
          # Update image tag in deployment manigest file
          yq -i '.spec.template.spec.containers[0].image = "aamirhussain3070/myapp:'"$SHORT_SHA"'"' ./k8s/pyapp-deployment.yml
        
      - name: Commit deployment file changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-action@noreply"
          git add k8s/pyapp-deployment.yml
          git commit -m "docker image tag updated in deployment file by pipeline for commit ${GITHUB_SHA::7}" || echo "No changes to commit"
          git push origin main
      